# Global Vars

- x86_64-07:
  cloud_name: x86_64-07
  docker_url: tcp://0.0.0.0:2375
  max_containers: 1
  docker_templates: !include docker_templates_amd64.yml

- lhg01:
  cloud_name: lhg-01
  docker-url: tcp://lhg-01:2375
  docker_templates:
    - xenial-amd64:
      docker_image_name: 'linaro/xenial'
      max_instances: '1'
      labels: 'docker-xenial-lhg'

